const {
  SENDGRID_TEMPLATE_CANCEL_SUBSCRIPTION,
  SENDGRID_TEMPLATE_INVITATION,
  SENDGRID_TEMPLATE_NEW_MESSAGE,
  SENDGRID_VERIFIED_SENDER,
} = require('../config/environment');

const from = {
  email: SENDGRID_VERIFIED_SENDER,
  name: 'Crio Team',
};

const templates = {
  CANCEL_SUBSCRIPTION: SENDGRID_TEMPLATE_CANCEL_SUBSCRIPTION,
  INVITATION: SENDGRID_TEMPLATE_INVITATION,
  NEW_MESSAGE: SENDGRID_TEMPLATE_NEW_MESSAGE,
};

module.exports = {
  from,
  templates,
};
